name: Continuous Integration

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  ci:
    name: Run Tests
    strategy:
      matrix:
        runner: ["ubuntu-20.04", "macos-11", "windows-2019"]
        include:
          - runner: ubuntu-20.04
            os: linux
            ext: ""
          - runner: macos-11
            os: macos
            ext: ""
          - runner: windows-2019
            os: windows
            ext: ".bat"
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Scala and Scala-CLI
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: scala-cli
      - name: Run Test
        shell: bash
        run: |
          # Windows needs help finding coursier installed apps
          #export PATH=$COURSIER_BIN_DIR:$PATH
          # First run of mill is important to set itself up
          ./mill resolve _
          scala-cli${{ matrix.ext }} test.sc -- ${{ matrix.os }}

