name: Continuous Integration

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  ci:
    name: Run Tests
    strategy:
      matrix:
        runner: ["ubuntu-20.04", "macos-11", "windows-2019"]
        include:
          - runner: ubuntu-20.04
            os: linux
            ext: ""
          - runner: macos-11
            os: macos
            ext: ""
          - runner: windows-2019
            os: windows
            ext: ".bat"
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Scala and Scala-CLI
        uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: scala-cli
      - name: Run Test
        shell: bash
        run: |
          # First run of mill is important to set itself up
          ./mill resolve _
          scala-cli${{ matrix.ext }} test.sc -- ${{ matrix.os }}

  publish:
    needs: [ci]
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Scala
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./mill -i io.kipp.mill.ci.release.ReleaseModule/publishAll
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
